name: 'gotestfmt'
description: 'Make your go test output beautiful.'
branding:
  icon: 'cast'
  color: 'orange'
inputs:
  token:
    description: 'GitHub token to avoid rate limiting.'
    required: false
    default: ''
  version:
    description: 'Which version of gofmt to download. Defaults to the latest.'
    required: false
    default: ''
  org:
    description: 'Organization to fetch gotestfmt from.'
    required: false
    default: 'GoTestTools'
  repo:
    description: 'Repository to fetch gotestfmt from.'
    required: false
    default: 'gotestfmt'
runs:
  using: 'node20'
  main: 'index.js'
