on:
  push:
  pull_request:
name: Self-test
jobs:
  self-test:
    name: Self-test
    runs-on: ubuntu-latest
    steps:
      - name: Install gotestfmt
        uses: haveyoudebuggedit/gotestfmt-action@main
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run gotestfmt
        working-directory: testdata
        run: go test -v ./... | gotestfmt
