on:
  pull_request:

name: Self-test
jobs:

  self-test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos', 'windows']

    runs-on: ${{ matrix.os }}-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gotestfmt
        uses: ./
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Run gotestfmt
        if: matrix.os != 'windows'
        working-directory: testdata
        run: |
          go test -json -v ./... 2>&1 | tee gotest.${{ matrix.os }}.log | gotestfmt

      - name: Run gotestfmt (Windows)
        if: matrix.os == 'windows'
        working-directory: testdata
        run: |
          go test -json -v ./... 2>&1 | Tee-Object gotest.${{ matrix.os }}.log | gotestfmt

      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log-${{ matrix.os }}
          path: gotest.${{ matrix.os }}.log
          if-no-files-found: error
