on:
  pull_request:
  push:

name: Self-test
jobs:

  self-test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos', 'windows']

    name: on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gotestfmt
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run gotestfmt on Windows
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          echo "%PATH%"
          go test -json -v ./... 2>&1 | gotestfmt.exe

      - name: Run gotestfmt
        working-directory: testdata
        shell: bash
        run: |
          go test -json -v ./... 2>&1 | tee gotest.${{ matrix.os }}.log | gotestfmt

      - name: Upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log-${{ matrix.os }}
          path: testdata/gotest.${{ matrix.os }}.log
          if-no-files-found: error
