on:
  push:
  pull_request:
name: Self-test
jobs:
  self-test:
    name: Self-test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install gotestfmt
        uses: ./
      - name: Run gotestfmt
        working-directory: testdata
        run: go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Upload test log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error